############
# Leagues
############

###
GET http://localhost:4004/football-league/leagues?
#&$expand=teams

###
POST http://localhost:4004/football-league/leagues
Content-Type: application/json

{
 "id": 3,
 "country": "FR",
 "name": "France Ligue 1",
 "level": 1
}

###
PATCH  http://localhost:4004/football-league/leagues/1
Content-Type: application/json

{
    "name": "La Liga"
}

############
# Teams
############

###
GET http://localhost:4004/football-league/teams?
#&$expand=players

###
POST http://localhost:4004/football-league/teams?
Content-Type: application/json

{
    "id": 5,
    "name": "Atlético Madrid",
    "stadiumName": "Wanda Metropolitano",
    "city": "Madrid",
    "footballLeague": {
        "id": 1
    }
}

###
PATCH http://localhost:4004/football-league/teams/5
Content-Type: application/json

{
    "city": "Barcelona"
}

############
# Players
############

###
GET http://localhost:4004/football-league/players

###
POST http://localhost:4004/football-league/players
Content-Type: application/json

{
    "id": 11122,
    "name": "Ter",
    "surname": "Stegen",
    "number": 34,
    "team": {
        "id": 1
    }
}

###
PATCH  http://localhost:4004/football-league/players/5
Content-Type: application/json
{
    "number": 13
}

